# â›”ï¸ DONT PUT SECRET FILES IN VCS
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: python-backend-database-url
  namespace: ai-tools
stringData:
  # TODO: Get the secrets from local ".env" file of "python-backend" folder 
  # and paste it here before deploying app by following "ğŸ—ï¸â˜¸ï¸ GKE (GCP): Deploy app on ğŸ› ï¸Staging and ğŸš€Prod Environments" section
  # or "ğŸ”â˜¸ï¸ GKE (GCP): Deploy App with CI&CD in K8s Cluster" section in "README.md" file.
  REDIS_URL: Secret-Placeholder
  MONGODB_URL: Secret-Placeholder
  CLERK_SECRET_KEY: Secret-Placeholder
  IMAGEKIT_PRIVATE_KEY: Secret-Placeholder
  RABBITMQ_URL: Secret-Placeholder
  KAFKA_BOOTSTRAP_SERVER: Secret-Placeholder
  KAFKA_SASL_USER_PASSWORD: Secret-Placeholder
  GRPC_HOST: go-backend
